# dbt format to recognize where sources are located and called
sources:
    - name: thc
      database: workshop-adk-francisco-borges
      schema: THC
      tables:
        - name: Orders
        - name: Sales
